### ISSUE TITLE
Installation instructions do not work for linux

### ISSUE THREAD

**Issue by daveycrocket** [astra-toolbox/astra-toolbox.github.io#4]
None of the instructions work.
"conda install -c astra-toolbox astra-toolbox" 
          doesn't find a package. PackageNotFoundError
"cd python/conda/libastra"
          There is no python in the root directory. There is no libastra folder at all and googling it doesn't get any results.

I even had a hard time running the conda environment for 2 days because I had a previous installation of python. This has been a really frustrating experience trying to use the toolbox.

**Comment by wjp** [comment]
I'm sorry to hear it's been a frustrating experience for you, but I can reproduce neither problem:

```
$ conda install -c astra-toolbox astra-toolbox
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/wjp/pkgs/miniconda3/envs/test123:

The following NEW packages will be INSTALLED:

    astra-toolbox: 1.8-np112py36_1    astra-toolbox
    libastra:      1.8-0              astra-toolbox
    libgfortran:   3.0.0-1                         
    mkl:           2017.0.3-0                      
    numpy:         1.12.1-py36_0                   
    scipy:         0.19.1-np112py36_0              
    six:           1.10.0-py36_0                   

Proceed ([y]/n)? 
```

And the `python/conda/libastra` directory is visible here for example:

https://github.com/astra-toolbox/astra-toolbox/tree/master/python/conda/libastra


We may be able to help if you can give more details about the problems you're seeing.

**Comment by daveycrocket** [comment]
Thanks so much for the reply. I finally figured it out. I had tried a
32-bit installation of conda hoping that would resolve my original issue.
But the package only exists for 64 bit. So once I installed conda 64-bit,
it worked.

**Comment by wjp** [comment]
Glad to hear it, and thanks for letting us know.
