### ISSUE TITLE
FDK_CUDA works with regular geometry but not with vector geometry

### ISSUE THREAD

**Issue by daveycrocket** [astra-toolbox/astra-toolbox.github.io#5]
I'm having calibration issues and wanted to try automatic calibration but I think that requires using the vector form of the projector geometry. I'm using cone beam with FDK_CUDA. The algorithm is successful if I use a regular geometry. But when I take the same geometry and convert it to vector for (proj_geom_vec = geom_2vec(proj_geom)), it fails with error "Configuration Error in CUDA_FDK: Error setting FDK geometry". All the algorithms (CGLS3D_CUDA. BP3D_CUDA and SIRT3D_CUDA) succeed with the the same vector geometry but those algorithms may have too much artifact and noise to use.

Do you think this is this due to it not being implemented or maybe a bug? I may try to debug it but setting up my build environment may take more time than I have.

**Comment by wjp** [comment]
In current master `FDK_CUDA` will accept `cone_vec` geometries, but not yet in the latest release.

Note that even in current master it might not do ``the right thing'' when giving it a general vec geometry, as it still makes some assumptions on the geometry. If you just translate the detector everything should be fine, but larger deviations from the standard circular cone geometry can move outside of the scope of the standard FDK algorithm.

**Comment by daveycrocket** [comment]
Thanks! The geometry is circular using a turntable but the physical setup is imperfect. Do you think I can resolve detector misalignment and turntable misalignment calibration by optimizing the vector geometries? The algorithms CGLS3D_CUDA. BP3D_CUDA and SIRT3D_CUDA have a lot of brightness artifact that make it hard to see signal through the noise. Although those issues may go away once I get the calibration right.

**Comment by wjp** [comment]
Yes, adjusting for misalignment is one of the main purposes of the `cone_vec` geometry. (And adjustments like this should also be generally fine with `FDK_CUDA` and `cone_vec` in master.)

**Comment by daveycrocket** [comment]
Thanks so much!

**Comment by daveycrocket** [comment]
I finally got it compiled from source and I can pass the vector geometry to the algorithm, but now the reconstruction results are all blank. They're blank for both vector and regular geometries for all algorithms. Pretty strange. Known issue?

**Comment by wjp** [comment]
I just double-checked, and current master is working fine for me. Do unmodified sample scripts (e.g., s003_gpu_reconstruction, s004_cpu_reconstruction.py, s007_3d_reconstruction.py) behave the same way? And what does `import astra; astra.test()` do? (Are you using python?)

**Comment by daveycrocket** [comment]
yep. python.
s004_cpu works. 
s003_gpu failed: Assertion 'e1 == cudaSuccess' failed.
s007_3d failed silently. All the images are black. 
astra.test() failed. Results:
       GPU info... GPU #0: GeForce GTX 580, with 1469MB
       Testing basic ting 
       Testing basic CPU 2D functionality... Ok
       Testing basic CUDA 2D functionality... Error
       Testing basic CUDA 3D functionality... Error
       Traceback (most recent call last):
         File "testastra.py", line 2, in <module>
           astra.test()
         File "/home/d/anaconda3/lib/python3.6/site-packages/astra/tests.py", line 104, in test
           test_CUDA()
         File "/home/d/anaconda3/lib/python3.6/site-packages/astra/tests.py", line 97, in test_CUDA
           raise RuntimeError("Test failed")
       RuntimeError: Test failed

**Comment by daveycrocket** [comment]
I'm thinking I have to go back to Cuda 8. I installed Cuda 9.1. I had to reinstall everything because my machine had issues I couldn't resolve when I was trying to compile it.

**Comment by daveycrocket** [comment]
That solved it. Cuda 9.1 doesn't work on my machine. 

In doing the testing I accidentally discovered that the reconstruction results are way better if I use the parallel3d geometry even though my actual setup is a cone beam. Any idea why that is?

**Comment by wjp** [comment]
Good to hear it's ok with cuda 8.

Regarding geometries, that sounds like the cone parameters are wrong. Common problems are the rotation direction (try flipping the order of the angles), or specifying the wrong source-origin/origin-detector distances.

**Comment by daveycrocket** [comment]
ok. I'll try that. Thanks for the help!!

**Comment by daveycrocket** [comment]
I've been reading through papers and trying to figure out the code for auto calibration without a phantom. The papers are tough to interpret though. Do you know of any existing code that does automatic calibration?

**Comment by daveycrocket** [comment]
awesome catch btw. most of my error was caused by the angles needing to be negative! As soon as I made them negative, I didn't even need much calibration adjustment.

**Comment by askorikov** [comment]
Closing for now. Please let us know if still relevant.
